export const myProjects = [
  {
    projectTitle: "react & css project",
    des: "This landing page project was created using React and Tailwind CSS to provide a modern and engaging user interface.",
    category: ["react", "css"],
    imgPath: "./images/landingPage.png",
    github: "https://github.com/OmarAlissa/modernUI/",
    link: "http://landingpage.omaralissa.de/",
  },
  {
    projectTitle: "Death Note Website",
    des: "This HTML & CSS page is inspired by the anime Death Note.",
    category: ["Html", "css"],
    imgPath: "./images/deathNote.png",
    github: "https://github.com/OmarAlissa/DEATH-NOTE",
    link: "https://deathnote.omaralissa.de/",
  },
  { projectTitle: "Movie Analysis", 
    category: ["python"], 
    des:"This is a Streamlit app for data dashboarding for a movie list.",
    imgPath: "./images/dashboard.png",
    github: "https://github.com/OmarAlissa/Dashboarding", 
    link: "https://github.com/OmarAlissa/Dashboarding", 
  },
  { projectTitle: "Chat With Pdfs", 
    category: ["python"], 
    des:"This is a Streamlit app for conversational PDF interaction empowered by the OpenAI API, RAG, and LangChain.",
    imgPath: "./images/chatWithPdf.png", 
    github: "https://github.com/OmarAlissa/CHAT_WITH_PDFs/tree/main/bot",
    link: "https://github.com/OmarAlissa/CHAT_WITH_PDFs/tree/main/bot",
  },
  { projectTitle: "Income calculator", 
    category: ["java"], 
    des:"This is a small income calculator program built with Java Swing.",
    imgPath: "./images/einnahmeRechner.png",
    github: "https://github.com/OmarAlissa/JAVA/tree/main/EinnahmenRechner",
    link: "https://github.com/OmarAlissa/JAVA/tree/main/EinnahmenRechner",
  },

  { projectTitle: "Depreciation Calculator", 
    category: ["java"], 
    des:"This is a small Java Swing program designed to calculate annual depreciation.",
    imgPath: "./images/abschreibung.png",
    github: "https://github.com/OmarAlissa/JAVA/tree/main/VC_Abschreibung2",
    link : "https://github.com/OmarAlissa/JAVA/tree/main/VC_Abschreibung2"
  },

];